- intercept: KEY_CAPSLOCK
  ontap: KEY_ESC
  onhold: KEY_LEFTCTRL

- intercept: KEY_TAB
  onhold:

  - {from: KEY_H, to: KEY_LEFT}
  - {from: KEY_J, to: KEY_DOWN}
  - {from: KEY_K, to: KEY_UP}
  - {from: KEY_L, to: KEY_RIGHT}
  - {from: KEY_G, to: KEY_DELETE}
  - {from: KEY_B, to: KEY_BACKSPACE}
  - {from: KEY_COMMA, to: KEY_HOME}
  - {from: KEY_DOT, to: KEY_END}

  - {from: KEY_1, to: KEY_F1}
  - {from: KEY_2, to: KEY_F2}
  - {from: KEY_3, to: KEY_F3}
  - {from: KEY_4, to: KEY_F4}
  - {from: KEY_5, to: KEY_F5}
  - {from: KEY_6, to: KEY_F6}
  - {from: KEY_7, to: KEY_F7}
  - {from: KEY_8, to: KEY_F8}
  - {from: KEY_9, to: KEY_F9}
  - {from: KEY_0, to: KEY_F10}
  - {from: KEY_MINUS, to: KEY_F11}
  - {from: KEY_EQUAL, to: KEY_F12}

  - {from: KEY_Q, to: KEY_1}
  - {from: KEY_W, to: KEY_2}
  - {from: KEY_E, to: KEY_3}
  - {from: KEY_R, to: KEY_4}
  - {from: KEY_T, to: KEY_5}
  - {from: KEY_Y, to: KEY_6}
  - {from: KEY_U, to: KEY_7}
  - {from: KEY_I, to: KEY_8}
  - {from: KEY_O, to: KEY_9}
  - {from: KEY_P, to: KEY_0}
  - {from: KEY_LEFTBRACKET, to: KEY_MINUS}
  - {from: KEY_RIGHTBRACKET, to: KEY_EQUAL}
